INSERT INTO animals (name) values ('Abyssinian');
INSERT INTO animals (name) values ('Adelie Penguin');
INSERT INTO animals (name) values ('Affenpinscher');
INSERT INTO animals (name) values ('Afghan Hound');
INSERT INTO animals (name) values ('African Bush Elephant');
INSERT INTO animals (name) values ('African Civet');
INSERT INTO animals (name) values ('African Clawed Frog');
INSERT INTO animals (name) values ('African Forest Elephant');
INSERT INTO animals (name) values ('African Palm Civet');
INSERT INTO animals (name) values ('African Penguin');
INSERT INTO animals (name) values ('African Tree Toad');
INSERT INTO animals (name) values ('African Wild Dog');
INSERT INTO animals (name) values ('Ainu Dog');
INSERT INTO animals (name) values ('Airedale Terrier');
INSERT INTO animals (name) values ('Akbash');
INSERT INTO animals (name) values ('Akita');
INSERT INTO animals (name) values ('Alaskan Malamute');
INSERT INTO animals (name) values ('Albatross');
INSERT INTO animals (name) values ('Aldabra Giant Tortoise');
INSERT INTO animals (name) values ('Alligator');
INSERT INTO animals (name) values ('Alpine Dachsbracke');
INSERT INTO animals (name) values ('American Bulldog');
INSERT INTO animals (name) values ('American Cocker Spaniel');
INSERT INTO animals (name) values ('American Coonhound');
INSERT INTO animals (name) values ('American Eskimo Dog');
INSERT INTO animals (name) values ('American Foxhound');
INSERT INTO animals (name) values ('American Pit Bull Terrier');
INSERT INTO animals (name) values ('American Staffordshire Terrier');
INSERT INTO animals (name) values ('American Water Spaniel');
INSERT INTO animals (name) values ('Anatolian Shepherd Dog');
INSERT INTO animals (name) values ('Angelfish');
INSERT INTO animals (name) values ('Ants');
INSERT INTO animals (name) values ('Anteater');
INSERT INTO animals (name) values ('Antelope');
INSERT INTO animals (name) values ('Appenzeller Dog');
INSERT INTO animals (name) values ('Arctic Fox');
INSERT INTO animals (name) values ('Arctic Hare');
INSERT INTO animals (name) values ('Arctic Wolf');
INSERT INTO animals (name) values ('Armadillo');
INSERT INTO animals (name) values ('Asian Elephant');
INSERT INTO animals (name) values ('Asian Giant Hornet');
INSERT INTO animals (name) values ('Asian Palm Civet');
INSERT INTO animals (name) values ('Asiatic Black Bear');
INSERT INTO animals (name) values ('Australian Cattle Dog');
INSERT INTO animals (name) values ('Australian Kelpie Dog');
INSERT INTO animals (name) values ('Australian Mist');
INSERT INTO animals (name) values ('Australian Shepherd');
INSERT INTO animals (name) values ('Australian Terrier');
INSERT INTO animals (name) values ('Avocet');
INSERT INTO animals (name) values ('Axolotl');
INSERT INTO animals (name) values ('Aye Aye');
INSERT INTO animals (name) values ('Baboon');
INSERT INTO animals (name) values ('Bactrian Camel');
INSERT INTO animals (name) values ('Badger');
INSERT INTO animals (name) values ('Balinese');
INSERT INTO animals (name) values ('Banded Palm Civet');
INSERT INTO animals (name) values ('Bandicoot');
INSERT INTO animals (name) values ('Barb');
INSERT INTO animals (name) values ('Barn Owl');
INSERT INTO animals (name) values ('Barnacle');
INSERT INTO animals (name) values ('Barracuda');
INSERT INTO animals (name) values ('Basenji Dog');
INSERT INTO animals (name) values ('Basking Shark');
INSERT INTO animals (name) values ('Basset Hound');
INSERT INTO animals (name) values ('Bat');
INSERT INTO animals (name) values ('Bavarian Mountain Hound');
INSERT INTO animals (name) values ('Beagle');
INSERT INTO animals (name) values ('Bear');
INSERT INTO animals (name) values ('Bearded Collie');
INSERT INTO animals (name) values ('Bearded Dragon');
INSERT INTO animals (name) values ('Beaver');
INSERT INTO animals (name) values ('Bedlington Terrier');
INSERT INTO animals (name) values ('Beetle');
INSERT INTO animals (name) values ('Bengal Tiger');
INSERT INTO animals (name) values ('Bernese Mountain Dog');
INSERT INTO animals (name) values ('Bichon Frise');
INSERT INTO animals (name) values ('Binturong');
INSERT INTO animals (name) values ('Bird');
INSERT INTO animals (name) values ('Birds Of Paradise');
INSERT INTO animals (name) values ('Birman');
INSERT INTO animals (name) values ('Bison');
INSERT INTO animals (name) values ('Black Bear');
INSERT INTO animals (name) values ('Black Rhinoceros');
INSERT INTO animals (name) values ('Black Russian Terrier');
INSERT INTO animals (name) values ('Black Widow Spider');
INSERT INTO animals (name) values ('Bloodhound');
INSERT INTO animals (name) values ('Blue Lacy Dog');
INSERT INTO animals (name) values ('Blue Whale');
INSERT INTO animals (name) values ('Bluetick Coonhound');
INSERT INTO animals (name) values ('Bobcat');
INSERT INTO animals (name) values ('Bolognese Dog');
INSERT INTO animals (name) values ('Bombay');
INSERT INTO animals (name) values ('Bongo');
INSERT INTO animals (name) values ('Bonobo');
INSERT INTO animals (name) values ('Booby');
INSERT INTO animals (name) values ('Border Collie');
INSERT INTO animals (name) values ('Border Terrier');
INSERT INTO animals (name) values ('Bornean Orang-utan');
INSERT INTO animals (name) values ('Borneo Elephant');
INSERT INTO animals (name) values ('Boston Terrier');
INSERT INTO animals (name) values ('Bottle Nosed Dolphin');
INSERT INTO animals (name) values ('Boxer Dog');
INSERT INTO animals (name) values ('Boykin Spaniel');
INSERT INTO animals (name) values ('Brazilian Terrier');
INSERT INTO animals (name) values ('Brown Bear');
INSERT INTO animals (name) values ('Budgerigar');
INSERT INTO animals (name) values ('Buffalo');
INSERT INTO animals (name) values ('Bull Mastiff');
INSERT INTO animals (name) values ('Bull Shark');
INSERT INTO animals (name) values ('Bull Terrier');
INSERT INTO animals (name) values ('Bull');
INSERT INTO animals (name) values ('Bulldog');
INSERT INTO animals (name) values ('Bullfrog');
INSERT INTO animals (name) values ('Bumble Bee');
INSERT INTO animals (name) values ('Burmese');
INSERT INTO animals (name) values ('Burrowing Frog');
INSERT INTO animals (name) values ('Butterfly');
INSERT INTO animals (name) values ('Butterfly Fish');
INSERT INTO animals (name) values ('Caiman');
INSERT INTO animals (name) values ('Caiman Lizard');
INSERT INTO animals (name) values ('Cairn Terrier');
INSERT INTO animals (name) values ('Camel');
INSERT INTO animals (name) values ('Canaan Dog');
INSERT INTO animals (name) values ('Capybara');
INSERT INTO animals (name) values ('Caracal');
INSERT INTO animals (name) values ('Carolina Dog');
INSERT INTO animals (name) values ('Cassowary');
INSERT INTO animals (name) values ('Cat');
INSERT INTO animals (name) values ('Caterpillar');
INSERT INTO animals (name) values ('Catfish');
INSERT INTO animals (name) values ('Cavalier King Charles Spaniel');
INSERT INTO animals (name) values ('Centipede');
INSERT INTO animals (name) values ('Cesky Fousek');
INSERT INTO animals (name) values ('Chameleon');
INSERT INTO animals (name) values ('Chamois');
INSERT INTO animals (name) values ('Cheetah');
INSERT INTO animals (name) values ('Chesapeake Bay Retriever');
INSERT INTO animals (name) values ('Chicken');
INSERT INTO animals (name) values ('Chihuahua');
INSERT INTO animals (name) values ('Chimpanzee');
INSERT INTO animals (name) values ('Chinchilla');
INSERT INTO animals (name) values ('Chinese Crested Dog');
INSERT INTO animals (name) values ('Chinook');
INSERT INTO animals (name) values ('Chinstrap Penguin');
INSERT INTO animals (name) values ('Chipmunk');
INSERT INTO animals (name) values ('Chow Chow');
INSERT INTO animals (name) values ('Cichlid');
INSERT INTO animals (name) values ('Clouded Leopard');
INSERT INTO animals (name) values ('Clown Fish');
INSERT INTO animals (name) values ('Clumber Spaniel');
INSERT INTO animals (name) values ('Coati');
INSERT INTO animals (name) values ('Cockroach');
INSERT INTO animals (name) values ('Collared Peccary');
INSERT INTO animals (name) values ('Collie');
INSERT INTO animals (name) values ('Common Buzzard');
INSERT INTO animals (name) values ('Common Frog');
INSERT INTO animals (name) values ('Common Loon');
INSERT INTO animals (name) values ('Common Toad');
INSERT INTO animals (name) values ('Coral');
INSERT INTO animals (name) values ('Cottontop Tamarin');
INSERT INTO animals (name) values ('Cougar');
INSERT INTO animals (name) values ('Cow');
INSERT INTO animals (name) values ('Coyote');
INSERT INTO animals (name) values ('Crab');
INSERT INTO animals (name) values ('Crab-Eating Macaque');
INSERT INTO animals (name) values ('Crane');
INSERT INTO animals (name) values ('Crested Penguin');
INSERT INTO animals (name) values ('Crocodile');
INSERT INTO animals (name) values ('Cross River Gorilla');
INSERT INTO animals (name) values ('Curly Coated Retriever');
INSERT INTO animals (name) values ('Cuscus');
INSERT INTO animals (name) values ('Cuttlefish');
INSERT INTO animals (name) values ('D');
INSERT INTO animals (name) values ('Dachshund');
INSERT INTO animals (name) values ('Dalmatian');
INSERT INTO animals (name) values ("Darwin\\'s Frog");
INSERT INTO animals (name) values ('Deer');
INSERT INTO animals (name) values ('Desert Tortoise');
INSERT INTO animals (name) values ('Deutsche Bracke');
INSERT INTO animals (name) values ('Dhole');
INSERT INTO animals (name) values ('Dingo');
INSERT INTO animals (name) values ('Discus');
INSERT INTO animals (name) values ('Doberman Pinscher');
INSERT INTO animals (name) values ('Dodo');
INSERT INTO animals (name) values ('Dog');
INSERT INTO animals (name) values ('Dogo Argentino');
INSERT INTO animals (name) values ('Dogue De Bordeaux');
INSERT INTO animals (name) values ('Dolphin');
INSERT INTO animals (name) values ('Donkey');
INSERT INTO animals (name) values ('Dormouse');
INSERT INTO animals (name) values ('Dragonfly');
INSERT INTO animals (name) values ('Drever');
INSERT INTO animals (name) values ('Duck');
INSERT INTO animals (name) values ('Dugong');
INSERT INTO animals (name) values ('Dunker');
INSERT INTO animals (name) values ('Dusky Dolphin');
INSERT INTO animals (name) values ('Dwarf Crocodile');
INSERT INTO animals (name) values ('Eagle');
INSERT INTO animals (name) values ('Earwig');
INSERT INTO animals (name) values ('Eastern Gorilla');
INSERT INTO animals (name) values ('Eastern Lowland Gorilla');
INSERT INTO animals (name) values ('Echidna');
INSERT INTO animals (name) values ('Edible Frogs');
INSERT INTO animals (name) values ('Egyptian Mau');
INSERT INTO animals (name) values ('Electric Eel');
INSERT INTO animals (name) values ('Elephant');
INSERT INTO animals (name) values ('Elephant Seal');
INSERT INTO animals (name) values ('Elephant Shrew');
INSERT INTO animals (name) values ('Emperor Penguin');
INSERT INTO animals (name) values ('Emperor Tamarin');
INSERT INTO animals (name) values ('Emu');
INSERT INTO animals (name) values ('English Cocker Spaniel');
INSERT INTO animals (name) values ('English Shepherd');
INSERT INTO animals (name) values ('English Springer Spaniel');
INSERT INTO animals (name) values ('Entlebucher Mountain Dog');
INSERT INTO animals (name) values ('Epagneul Pont Audemer');
INSERT INTO animals (name) values ('Eskimo Dog');
INSERT INTO animals (name) values ('Estrela Mountain Dog');
INSERT INTO animals (name) values ('Falcon');
INSERT INTO animals (name) values ('Fennec Fox');
INSERT INTO animals (name) values ('Ferret');
INSERT INTO animals (name) values ('Field Spaniel');
INSERT INTO animals (name) values ('Fin Whale');
INSERT INTO animals (name) values ('Finnish Spitz');
INSERT INTO animals (name) values ('Fire-Bellied Toad');
INSERT INTO animals (name) values ('Fish');
INSERT INTO animals (name) values ('Fishing Cat');
INSERT INTO animals (name) values ('Flamingo');
INSERT INTO animals (name) values ('Flat Coat Retriever');
INSERT INTO animals (name) values ('Flounder');
INSERT INTO animals (name) values ('Fly');
INSERT INTO animals (name) values ('Flying Squirrel');
INSERT INTO animals (name) values ('Fossa');
INSERT INTO animals (name) values ('Fox');
INSERT INTO animals (name) values ('Fox Terrier');
INSERT INTO animals (name) values ('French Bulldog');
INSERT INTO animals (name) values ('Frigatebird');
INSERT INTO animals (name) values ('Frilled Lizard');
INSERT INTO animals (name) values ('Frog');
INSERT INTO animals (name) values ('Fur Seal');
INSERT INTO animals (name) values ('Galapagos Penguin');
INSERT INTO animals (name) values ('Galapagos Tortoise');
INSERT INTO animals (name) values ('Gar');
INSERT INTO animals (name) values ('Gecko');
INSERT INTO animals (name) values ('Gentoo Penguin');
INSERT INTO animals (name) values ('Geoffroys Tamarin');
INSERT INTO animals (name) values ('Gerbil');
INSERT INTO animals (name) values ('German Pinscher');
INSERT INTO animals (name) values ('German Shepherd');
INSERT INTO animals (name) values ('Gharial');
INSERT INTO animals (name) values ('Giant African Land Snail');
INSERT INTO animals (name) values ('Giant Clam');
INSERT INTO animals (name) values ('Giant Panda Bear');
INSERT INTO animals (name) values ('Giant Schnauzer');
INSERT INTO animals (name) values ('Gibbon');
INSERT INTO animals (name) values ('Gila Monster');
INSERT INTO animals (name) values ('Giraffe');
INSERT INTO animals (name) values ('Glass Lizard');
INSERT INTO animals (name) values ('Glow Worm');
INSERT INTO animals (name) values ('Goat');
INSERT INTO animals (name) values ('Golden Lion Tamarin');
INSERT INTO animals (name) values ('Golden Oriole');
INSERT INTO animals (name) values ('Golden Retriever');
INSERT INTO animals (name) values ('Goose');
INSERT INTO animals (name) values ('Gopher');
INSERT INTO animals (name) values ('Gorilla');
INSERT INTO animals (name) values ('Grasshopper');
INSERT INTO animals (name) values ('Great Dane');
INSERT INTO animals (name) values ('Great White Shark');
INSERT INTO animals (name) values ('Greater Swiss Mountain Dog');
INSERT INTO animals (name) values ('Green Bee-Eater');
INSERT INTO animals (name) values ('Greenland Dog');
INSERT INTO animals (name) values ('Grey Mouse Lemur');
INSERT INTO animals (name) values ('Grey Reef Shark');
INSERT INTO animals (name) values ('Grey Seal');
INSERT INTO animals (name) values ('Greyhound');
INSERT INTO animals (name) values ('Grizzly Bear');
INSERT INTO animals (name) values ('Grouse');
INSERT INTO animals (name) values ('Guinea Fowl');
INSERT INTO animals (name) values ('Guinea Pig');
INSERT INTO animals (name) values ('Guppy');
INSERT INTO animals (name) values ('Hammerhead Shark');
INSERT INTO animals (name) values ('Hamster');
INSERT INTO animals (name) values ('Hare');
INSERT INTO animals (name) values ('Harrier');
INSERT INTO animals (name) values ('Havanese');
INSERT INTO animals (name) values ('Hedgehog');
INSERT INTO animals (name) values ('Hercules Beetle');
INSERT INTO animals (name) values ('Hermit Crab');
INSERT INTO animals (name) values ('Heron');
INSERT INTO animals (name) values ('Highland Cattle');
INSERT INTO animals (name) values ('Himalayan');
INSERT INTO animals (name) values ('Hippopotamus');
INSERT INTO animals (name) values ('Honey Bee');
INSERT INTO animals (name) values ('Horn Shark');
INSERT INTO animals (name) values ('Horned Frog');
INSERT INTO animals (name) values ('Horse');
INSERT INTO animals (name) values ('Horseshoe Crab');
INSERT INTO animals (name) values ('Howler Monkey');
INSERT INTO animals (name) values ('Human');
INSERT INTO animals (name) values ('Humboldt Penguin');
INSERT INTO animals (name) values ('Hummingbird');
INSERT INTO animals (name) values ('Humpback Whale');
INSERT INTO animals (name) values ('Hyena');
INSERT INTO animals (name) values ('Ibis');
INSERT INTO animals (name) values ('Ibizan Hound');
INSERT INTO animals (name) values ('Iguana');
INSERT INTO animals (name) values ('Impala');
INSERT INTO animals (name) values ('Indian Elephant');
INSERT INTO animals (name) values ('Indian Palm Squirrel');
INSERT INTO animals (name) values ('Indian Rhinoceros');
INSERT INTO animals (name) values ('Indian Star Tortoise');
INSERT INTO animals (name) values ('Indochinese Tiger');
INSERT INTO animals (name) values ('Indri');
INSERT INTO animals (name) values ('Insect');
INSERT INTO animals (name) values ('Irish Setter');
INSERT INTO animals (name) values ('Irish WolfHound');
INSERT INTO animals (name) values ('J');
INSERT INTO animals (name) values ('Jack Russel');
INSERT INTO animals (name) values ('Jackal');
INSERT INTO animals (name) values ('Jaguar');
INSERT INTO animals (name) values ('Japanese Chin');
INSERT INTO animals (name) values ('Japanese Macaque');
INSERT INTO animals (name) values ('Javan Rhinoceros');
INSERT INTO animals (name) values ('Javanese');
INSERT INTO animals (name) values ('Jellyfish');
INSERT INTO animals (name) values ('Kakapo');
INSERT INTO animals (name) values ('Kangaroo');
INSERT INTO animals (name) values ('Keel Billed Toucan');
INSERT INTO animals (name) values ('Killer Whale');
INSERT INTO animals (name) values ('King Crab');
INSERT INTO animals (name) values ('King Penguin');
INSERT INTO animals (name) values ('Kingfisher');
INSERT INTO animals (name) values ('Kiwi');
INSERT INTO animals (name) values ('Koala');
INSERT INTO animals (name) values ('Komodo Dragon');
INSERT INTO animals (name) values ('Kudu');
INSERT INTO animals (name) values ('Labradoodle');
INSERT INTO animals (name) values ('Labrador Retriever');
INSERT INTO animals (name) values ('Ladybird');
INSERT INTO animals (name) values ('Leaf-Tailed Gecko');
INSERT INTO animals (name) values ('Lemming');
INSERT INTO animals (name) values ('Lemur');
INSERT INTO animals (name) values ('Leopard');
INSERT INTO animals (name) values ('Leopard Cat');
INSERT INTO animals (name) values ('Leopard Seal');
INSERT INTO animals (name) values ('Leopard Tortoise');
INSERT INTO animals (name) values ('Liger');
INSERT INTO animals (name) values ('Lion');
INSERT INTO animals (name) values ('Lionfish');
INSERT INTO animals (name) values ('Little Penguin');
INSERT INTO animals (name) values ('Lizard');
INSERT INTO animals (name) values ('Llama');
INSERT INTO animals (name) values ('Lobster');
INSERT INTO animals (name) values ('Long-Eared Owl');
INSERT INTO animals (name) values ('Lynx');
INSERT INTO animals (name) values ('Macaroni Penguin');
INSERT INTO animals (name) values ('Macaw');
INSERT INTO animals (name) values ('Magellanic Penguin');
INSERT INTO animals (name) values ('Magpie');
INSERT INTO animals (name) values ('Maine Coon');
INSERT INTO animals (name) values ('Malayan Civet');
INSERT INTO animals (name) values ('Malayan Tiger');
INSERT INTO animals (name) values ('Maltese');
INSERT INTO animals (name) values ('Manatee');
INSERT INTO animals (name) values ('Mandrill');
INSERT INTO animals (name) values ('Manta Ray');
INSERT INTO animals (name) values ('Marine Toad');
INSERT INTO animals (name) values ('Markhor');
INSERT INTO animals (name) values ('Marsh Frog');
INSERT INTO animals (name) values ('Masked Palm Civet');
INSERT INTO animals (name) values ('Mastiff');
INSERT INTO animals (name) values ('Mayfly');
INSERT INTO animals (name) values ('Meerkat');
INSERT INTO animals (name) values ('Millipede');
INSERT INTO animals (name) values ('Minke Whale');
INSERT INTO animals (name) values ('Mole');
INSERT INTO animals (name) values ('Molly');
INSERT INTO animals (name) values ('Mongoose');
INSERT INTO animals (name) values ('Mongrel');
INSERT INTO animals (name) values ('Monitor Lizard');
INSERT INTO animals (name) values ('Monkey');
INSERT INTO animals (name) values ('Monte Iberia Eleuth');
INSERT INTO animals (name) values ('Moorhen');
INSERT INTO animals (name) values ('Moose');
INSERT INTO animals (name) values ('Moray Eel');
INSERT INTO animals (name) values ('Moth');
INSERT INTO animals (name) values ('Mountain Gorilla');
INSERT INTO animals (name) values ('Mountain Lion');
INSERT INTO animals (name) values ('Mouse');
INSERT INTO animals (name) values ('Mule');
INSERT INTO animals (name) values ('Neanderthal');
INSERT INTO animals (name) values ('Neapolitan Mastiff');
INSERT INTO animals (name) values ('Newfoundland');
INSERT INTO animals (name) values ('Newt');
INSERT INTO animals (name) values ('Nightingale');
INSERT INTO animals (name) values ('Norfolk Terrier');
INSERT INTO animals (name) values ('Norwegian Forest');
INSERT INTO animals (name,wikipedia) values ('Numbats','https://en.wikipedia.org/wiki/Numbat');
INSERT INTO animals (name,wikipedia) values ('Nurse Shark','https://en.wikipedia.org/wiki/Nurse_shark');
INSERT INTO animals (name,wikipedia) values ('Ocelots','https://en.wikipedia.org/wiki/Ocelot');
INSERT INTO animals (name,wikipedia) values ('Octopus','https://en.wikipedia.org/wiki/Octopus');
INSERT INTO animals (name,wikipedia) values ('Okapi','https://en.wikipedia.org/wiki/Okapi');
INSERT INTO animals (name) values ('Old English Sheepdog');
INSERT INTO animals (name) values ('Olm');
INSERT INTO animals (name) values ('Opossum');
INSERT INTO animals (name) values ('Orang-utan');
INSERT INTO animals (name) values ('Ostrich');
INSERT INTO animals (name) values ('Otter');
INSERT INTO animals (name) values ('Oyster');
INSERT INTO animals (name) values ('Pademelon');
INSERT INTO animals (name) values ('Panther');
INSERT INTO animals (name) values ('Parrot');
INSERT INTO animals (name) values ('Patas Monkey');
INSERT INTO animals (name) values ('Peacock');
INSERT INTO animals (name) values ('Pekingese');
INSERT INTO animals (name) values ('Pelican');
INSERT INTO animals (name) values ('Penguin');
INSERT INTO animals (name) values ('Persian');
INSERT INTO animals (name) values ('Pheasant');
INSERT INTO animals (name) values ('Pied Tamarin');
INSERT INTO animals (name) values ('Pig');
INSERT INTO animals (name) values ('Pika');
INSERT INTO animals (name) values ('Pike');
INSERT INTO animals (name) values ('Pink Fairy Armadillo');
INSERT INTO animals (name) values ('Piranha');
INSERT INTO animals (name) values ('Platypus');
INSERT INTO animals (name) values ('Pointer');
INSERT INTO animals (name) values ('Poison Dart Frog');
INSERT INTO animals (name) values ('Polar Bear');
INSERT INTO animals (name) values ('Pond Skater');
INSERT INTO animals (name) values ('Poodle');
INSERT INTO animals (name) values ('Pool Frog');
INSERT INTO animals (name) values ('Porcupine');
INSERT INTO animals (name) values ('Possum');
INSERT INTO animals (name) values ('Prawn');
INSERT INTO animals (name) values ('Proboscis Monkey');
INSERT INTO animals (name) values ('Puffer Fish');
INSERT INTO animals (name) values ('Puffin');
INSERT INTO animals (name) values ('Pug');
INSERT INTO animals (name) values ('Salmon');
INSERT INTO animals (name) values ('Puma');
INSERT INTO animals (name) values ('Purple Emperor');
INSERT INTO animals (name) values ('Puss Moth');
INSERT INTO animals (name) values ('Pygmy Hippopotamus');
INSERT INTO animals (name) values ('Pygmy Marmoset');
INSERT INTO animals (name) values ('Quail');
INSERT INTO animals (name) values ('Quetzal');
INSERT INTO animals (name) values ('Quokka');
INSERT INTO animals (name) values ('Quoll');
INSERT INTO animals (name) values ('Rabbit');
INSERT INTO animals (name) values ('Raccoon');
INSERT INTO animals (name) values ('Raccoon Dog');
INSERT INTO animals (name) values ('Radiated Tortoise');
INSERT INTO animals (name) values ('Ragdoll');
INSERT INTO animals (name) values ('Rat');
INSERT INTO animals (name) values ('Rattlesnake');
INSERT INTO animals (name) values ('Red Knee Tarantula');
INSERT INTO animals (name) values ('Red Panda');
INSERT INTO animals (name) values ('Red Wolf');
INSERT INTO animals (name) values ('Red-handed Tamarin');
INSERT INTO animals (name) values ('Reindeer');
INSERT INTO animals (name) values ('Rhinoceros');
INSERT INTO animals (name) values ('River Dolphin');
INSERT INTO animals (name) values ('River Turtle');
INSERT INTO animals (name) values ('Robin');
INSERT INTO animals (name) values ('Rock Hyrax');
INSERT INTO animals (name) values ('Rockhopper Penguin');
INSERT INTO animals (name) values ('Roseate Spoonbill');
INSERT INTO animals (name) values ('Rottweiler');
INSERT INTO animals (name) values ('Royal Penguin');
INSERT INTO animals (name) values ('Russian Blue');
INSERT INTO animals (name) values ('Sabre-Toothed Tiger');
INSERT INTO animals (name) values ('Saint Bernard');
INSERT INTO animals (name) values ('Salamander');
INSERT INTO animals (name) values ('Sand Lizard');
INSERT INTO animals (name) values ('Saola');
INSERT INTO animals (name) values ('Scorpion');
INSERT INTO animals (name) values ('Scorpion Fish');
INSERT INTO animals (name) values ('Sea Dragon');
INSERT INTO animals (name) values ('Sea Lion');
INSERT INTO animals (name) values ('Sea Otter');
INSERT INTO animals (name) values ('Sea Slug');
INSERT INTO animals (name) values ('Sea Squirt');
INSERT INTO animals (name) values ('Sea Turtle');
INSERT INTO animals (name) values ('Sea Urchin');
INSERT INTO animals (name) values ('Seahorse');
INSERT INTO animals (name) values ('Seal');
INSERT INTO animals (name) values ('Serval');
INSERT INTO animals (name) values ('Sheep');
INSERT INTO animals (name) values ('Shih Tzu');
INSERT INTO animals (name) values ('Shrimp');
INSERT INTO animals (name) values ('Siamese');
INSERT INTO animals (name) values ('Siamese Fighting Fish');
INSERT INTO animals (name) values ('Siberian');
INSERT INTO animals (name) values ('Siberian Husky');
INSERT INTO animals (name) values ('Siberian Tiger');
INSERT INTO animals (name) values ('Silver Dollar');
INSERT INTO animals (name) values ('Skunk');
INSERT INTO animals (name) values ('Sloth');
INSERT INTO animals (name) values ('Slow Worm');
INSERT INTO animals (name) values ('Snail');
INSERT INTO animals (name) values ('Snake');
INSERT INTO animals (name) values ('Snapping Turtle');
INSERT INTO animals (name) values ('Snowshoe');
INSERT INTO animals (name) values ('Snowy Owl');
INSERT INTO animals (name) values ('Somali');
INSERT INTO animals (name) values ('South China Tiger');
INSERT INTO animals (name) values ('Spadefoot Toad');
INSERT INTO animals (name) values ('Sparrow');
INSERT INTO animals (name) values ('Spectacled Bear');
INSERT INTO animals (name) values ('Sperm Whale');
INSERT INTO animals (name) values ('Spider Monkey');
INSERT INTO animals (name) values ('Spiny Dogfish');
INSERT INTO animals (name) values ('Sponge');
INSERT INTO animals (name) values ('Squid');
INSERT INTO animals (name) values ('Squirrel');
INSERT INTO animals (name) values ('Squirrel Monkey');
INSERT INTO animals (name) values ('Sri Lankan Elephant');
INSERT INTO animals (name) values ('Staffordshire Bull Terrier');
INSERT INTO animals (name) values ('Stag Beetle');
INSERT INTO animals (name) values ('Starfish');
INSERT INTO animals (name) values ('Stellers Sea Cow');
INSERT INTO animals (name) values ('Stick Insect');
INSERT INTO animals (name) values ('Stingray');
INSERT INTO animals (name) values ('Stoat');
INSERT INTO animals (name) values ('Striped Rocket Frog');
INSERT INTO animals (name) values ('Sumatran Elephant');
INSERT INTO animals (name) values ('Sumatran Orang-utan');
INSERT INTO animals (name) values ('Sumatran Rhinoceros');
INSERT INTO animals (name) values ('Sumatran Tiger');
INSERT INTO animals (name) values ('Sun Bear');
INSERT INTO animals (name) values ('Swan');
INSERT INTO animals (name) values ('Tang');
INSERT INTO animals (name) values ('Tapir');
INSERT INTO animals (name) values ('Tarsier');
INSERT INTO animals (name) values ('Tasmanian Devil');
INSERT INTO animals (name) values ('Tawny Owl');
INSERT INTO animals (name) values ('Termite');
INSERT INTO animals (name) values ('Tetra');
INSERT INTO animals (name) values ('Thorny Devil');
INSERT INTO animals (name) values ('Tibetan Mastiff');
INSERT INTO animals (name) values ('Tiffany');
INSERT INTO animals (name) values ('Tiger');
INSERT INTO animals (name) values ('Tiger Salamander');
INSERT INTO animals (name) values ('Tiger Shark');
INSERT INTO animals (name) values ('Tortoise');
INSERT INTO animals (name) values ('Toucan');
INSERT INTO animals (name) values ('Tree Frog');
INSERT INTO animals (name) values ('Tropicbird');
INSERT INTO animals (name) values ('Tuatara');
INSERT INTO animals (name) values ('Turkey');
INSERT INTO animals (name) values ('Turkish Angora');
INSERT INTO animals (name) values ('Uakari');
INSERT INTO animals (name) values ('Uguisu');
INSERT INTO animals (name) values ('Umbrellabird');
INSERT INTO animals (name) values ('Vampire Bat');
INSERT INTO animals (name) values ('Vervet Monkey');
INSERT INTO animals (name) values ('Vulture');
INSERT INTO animals (name) values ('Wallaby');
INSERT INTO animals (name) values ('Walrus');
INSERT INTO animals (name) values ('Warthog');
INSERT INTO animals (name) values ('Wasp');
INSERT INTO animals (name) values ('Water Buffalo');
INSERT INTO animals (name) values ('Water Dragon');
INSERT INTO animals (name) values ('Water Vole');
INSERT INTO animals (name) values ('Weasel');
INSERT INTO animals (name) values ('Welsh Corgi');
INSERT INTO animals (name) values ('West Highland Terrier');
INSERT INTO animals (name) values ('Western Gorilla');
INSERT INTO animals (name) values ('Western Lowland Gorilla');
INSERT INTO animals (name) values ('Whale Shark');
INSERT INTO animals (name) values ('Whippet');
INSERT INTO animals (name) values ('White Faced Capuchin');
INSERT INTO animals (name) values ('White Rhinoceros');
INSERT INTO animals (name) values ('White Tiger');
INSERT INTO animals (name) values ('Wild Boar');
INSERT INTO animals (name) values ('Wildebeest');
INSERT INTO animals (name) values ('Wolf');
INSERT INTO animals (name) values ('Wolverine');
INSERT INTO animals (name) values ('Wombat');
INSERT INTO animals (name) values ('Woodlouse');
INSERT INTO animals (name) values ('Woodpecker');
INSERT INTO animals (name) values ('Woolly Mammoth');
INSERT INTO animals (name) values ('Woolly Monkey');
INSERT INTO animals (name) values ('Wrasse');
INSERT INTO animals (name) values ('X-Ray Tetra');
INSERT INTO animals (name) values ('Yak');
INSERT INTO animals (name) values ('Yellow-Eyed Penguin');
INSERT INTO animals (name) values ('Yorkshire Terrier');
INSERT INTO animals (name) values ('Zebra');
INSERT INTO animals (name) values ('Zebra Shark');
INSERT INTO animals (name) values ('Zebu');
INSERT INTO animals (name) values ('Zonkey');
INSERT INTO animals (name) values ('Zorse');
INSERT INTO animals (name) values ('Trout');
INSERT INTO animals (name) values ('Goldf fish');
INSERT INTO animals (name) values ('Shark');
